config/routes.rb
SppForum::Application.routes.draw do

  

  devise_for :users,  :controllers => { :registrations => :users}
  
  resources :users
  resources :articles

  resources :forums do 
    resources :forum_threads
  end


  resources :forum_posts
  resources :forum_threads do
    resources :forum_posts
  end
  root :to => "articles#index"

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :forum_threads
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    if can?(:read, Forum)
      @forums = Forum.all
      @authorized = true
    else
      @forums = []
      @authorized = false
    end
    # authorize! :read, Forum
  end

  def show
    @forum = Forum.find(params[:id]) if can?(:read, Forum)
    authorize! :read, Forum
  end

  def new
    @forum = Forum.new if can?(:create, Forum)
    authorize! :create, Forum
  end

  def create
    @forum = Forum.new(params[:forum])
    respond_to do |format|
      if can?(:create, Forum) and @forum.save
        format.html { redirect_to(forum_path(@forum), :notice=>"Forum was saved successfully") }
        format.js
      else
        flash[:notice] = "Something went wrong"
        format.html { render :action => "new" }
      end
    end
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_navigation.erb
<% if type == :forum %>
  <li>
  <%= link_to "All forums", forums_path %> / <strong><%= forum.name %></strong>
  </li>
<% elsif type == :thread %>
  <li>
  <%= link_to "All forums", forums_path %> / <%= link_to forum.name, forum %> / <strong><%= thread.title %></strong>
  </li>
<% elsif type == :edit_thread %>
  <li>
  <%= link_to "All forums", forums_path %> / <%= link_to forum.name, forum %> / <%= link_to thread.title, thread %> / <strong>Edit thread</strong>
  </li>
<% elsif type == :new_thread %>
  <li>
  <%= link_to "All forums", forums_path %> / <%= link_to forum.name, forum %> / <strong>New thread</strong>
  </li>
<% elsif type == :edit_post %>
  <li>
  <%= link_to "All forums", forums_path %> / <%= link_to post.forum_thread.forum.name, post.forum_thread.forum %> / <%= link_to post.forum_thread.title, post.forum_thread %> / <strong>Edit "<%= post.title %>"</strong>
  </li>
<% elsif type == :new_post %>
  <li>
  <%= link_to "All forums", forums_path %> / <%= link_to thread.forum.name, thread.forum %> / <%= link_to thread.title, thread %> / <strong>New reply</strong>
  </li>
<% elsif type == :all_forums %>
  <li>
  <strong>All forums</strong>
  </li>
<% elsif type == :new_forum %>
  <li>
  <%= link_to "All forums", forums_path %> / <strong>New forum</strong>
  </li>
<% elsif type == :show_user or type == :all_users or type == :edit_user or type == :new_user %>
  <li>
  <%= link_to "All forums", forums_path %>
  </li>
<% end %>

app/views/forums/index.html.erb
<%= nav_links(render 'users/user_login_info') %>
<%= subnav_links(render :partial => "forums/navigation", :locals => {:type => :all_forums}) %>

<% if can?(:create, Forum) %>
  <p>
  <%= link_to "New Forum", new_forum_path %>
  </p>
<% end %>

<table id="forum_table">
  <thead>
    <tr>
      <th class="forum_th"></th>
    </tr>
  </thead>
  <tbody>
    <% if !@authorized %>
      <tr>
        <td class="forum_td"><strong>Welcome to the Forums!</strong><br />You have to log in above to be able to read posts and participate in the discussion.</td>
      </tr>
    <% end %>
    <% for forum in @forums
        threads = forum.forum_threads
        thread_nr = (threads).length %>
      <tr>
        <td class="forum_td"><strong><%= link_to forum.name, forum %></strong> (<%= thread_nr %> threads)<br /><%= forum.description %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <th class="forum_th"></th>
  </tfoot>
</table>

app/views/forums/new.html.erb
<%= nav_links(render 'users/user_login_info') %>
<%= subnav_links(render :partial => "forums/navigation", :locals => {:type => :new_forum}) %>

<%=form_for @forum do |f|%>
  <p>
  <strong>Name</strong><br />
  <%=f.text_field :name %><br />
  </p>

  <p>
  <strong>Description</strong><br />
  <%=f.text_area :description %>
  </p>

  <p>
  <%=f.submit "Create Forum"%>
  </p>
<%end%>

app/views/forums/show.html.erb
<%= nav_links(render 'users/user_login_info') %>
<%= subnav_links(render :partial => "forums/navigation", :locals => {:type => :forum, :forum => @forum}) %>

<% if can?(:create, ForumThread) %>
  <p>
  <%= link_to "New thread", new_forum_forum_thread_path(@forum) %>
  </p>
<% end %>

<table id="forum_table">
  <thead>
  <tr>
    <th class="thread_th">Thread</th>
    <th class="thread_th">Message</th>
    <th class="thread_th">#Replies</th>
  </tr>
  </thead>
  <tbody>
  <% @forum.forum_threads.each do |f| %>
  <tr>
    <td class="forum_td"><%=link_to f.title, forum_thread_path(f)%></td>
    <td class="forum_td"><%= f.body %></td>
    <td class="forum_td"><%=f.forum_posts.size%></td>
  <tr>
  <% end %>
  </tbody>
</table>