config/routes.rb
SppForum::Application.routes.draw do

  

  devise_for :users,  :controllers => { :registrations => :users}
  
  resources :users
  resources :articles

  resources :forums do 
    resources :forum_threads
  end


  resources :forum_posts
  resources :forum_threads do
    resources :forum_posts
  end
  root :to => "articles#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :picture, :url => ":class/:attachment/:id/:style.:extension",:path =>":rails_root/public/images/:class/:attachment/:id/:style.:extension", :styles => { :medium => "300x300>",:thumb => "100x100>" }

  validate :email, :uniqueness => true

  has_and_belongs_to_many :roles
  has_many :forum_posts

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable  and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :surname, :description, :picture

  def role?(role)
    self.roles.where(:name => role.to_s.downcase).exists?
  end

  def name
    "#{firstname} #{surname}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show,:new,:destroy,:edit,:update]

  # GET /users
  # GET /users.xml                                                
  # GET /users.json                                       HTML and AJAX
  #-----------------------------------------------------------------------
  def index
    if can?(:read, User)
      @users = User.accessible_by(current_ability, :index)
    else
      @users = []
    end
    respond_to do |format|
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
      format.html
    end
  end

  # GET /users/new
  # GET /users/new.xml                                            
  # GET /users/new.json                                    HTML AND AJAX
  #-------------------------------------------------------------------
  def new
		@roles_new = Role.all
		if can?(:update, Role)
			@roles_new = Role.all
		end

    @user = User.new if can?(:create, User)
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
  end

  # GET /users/1
  # GET /users/1.xml                                                       
  # GET /users/1.json                                     HTML AND AJAX
  #-------------------------------------------------------------------
  def show
    if can?(:read, User)
      @user = User.find(params[:id])
      @roles = ""

      @user.roles.each do |role|
        if @roles == ""
          @roles += role.name
        else
          @roles += ", " + role.name
        end
      end
    end

    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html      
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # GET /users/1/edit                                                      
  # GET /users/1/edit.xml                                                      
  # GET /users/1/edit.json                                HTML AND AJAX
  #-------------------------------------------------------------------
  def edit
    @user = User.find(params[:id])
    if can?(:update, @user)
      @roles = ""

      @user.roles.each do |role|
        if @roles == ""
          @roles += role.name
        else
          @roles += ", " + role.name
        end
      end
    else
      @user = nil
    end

    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # DELETE /users/1     
  # DELETE /users/1.xml
  # DELETE /users/1.json                                  HTML AND AJAX
  #-------------------------------------------------------------------
  def destroy
    @user.destroy! if can?(:destroy, User)

    respond_to do |format|
      format.json { respond_to_destroy(:ajax) }
      format.xml  { head :ok }
      format.html { respond_to_destroy(:html) }      
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # POST /users
  # POST /users.xml         
  # POST /users.json                                      HTML AND AJAX
  #-----------------------------------------------------------------
  def create
    if can?(:create, User)
      @user = User.new(params[:user])
      password_unencrypted = params[:user][:password]
      role = Role.where(:name => "normal")
      if role == nil or role.empty?
        role = Role.new
        role.name = "normal"
        role.save
      end
      @user.roles.push(role)
    end

    if can?(:create, User) and @user.save
      respond_to do |format|
        ForumMailer.welcome_email(@user, password_unencrypted).deliver
        format.json { render :json => @user.to_json, :status => 200, :text => "User was created!" }
        format.xml  { head :ok }
        format.html { redirect_to :action => :index }
      end
    else
      respond_to do |format|
        format.json { render :text => "Could not create user.", :status => :unprocessable_entity } # placeholder
        format.xml  { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  # PUT /users/1.json
  
  def update
    @user = User.find(params[:id])

    # If you can manage users: Always provide your own password to verify changes 
    # Else: Provide the user's password
    valid_password = false
    if (can?(:manage, User))
      valid_current_password = current_user.valid_password?(params[:user][:current_password])
    else
      valid_current_password = @user.valid_password?(params[:user][:current_password])
    end

    @user.errors[:base] << "The password you entered is incorrect" unless valid_current_password
    if params[:user][:password].blank?
      [:password,:password_confirmation,:current_password].collect {|p| params[:user].delete(p)}  
    end

    respond_to do |format|
      if can?(:update, User) and @user.errors[:base].empty? && @user.update_attributes(params[:user])
        flash[:notice] = "Your account has been updated"
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { redirect_to(@user) }
      else
        format.json { render :text => "Could not update user", :status => :unprocessable_entity } #placeholder
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.html { render :action => :edit, :status => :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end

  # Get roles accessible by the current user
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability, :read)
  end

  # Make the current user object available to views
  def get_user
    @current_user = current_user
  end

end

app/views/users/_user_fields.html.erb
<%= debug roles_new %>

<p>Profile picture</p>
<p><%= image_tag @user.picture.url(:medium) %></p>
<p><%= f.file_field :picture %></p>

<p><%= f.label :firstname %></p>
<p><%= f.text_field :firstname %></p>

<p><%= f.label :surname %></p>
<p><%= f.text_field :surname %></p>

<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>

<p>Description of yourself</p>
<p><%= f.text_area :description %></p>

<% if can? :read, Role %>
  <p><%= f.label :roles %></p>
  <p><%= roles %></p>
<% end %>

<% if can? :update, Role %>
  <p>Select role for user</p>
  <p><%= select_tag "roles_new", options_from_collection_for_select(roles_new, "id", "name") %></p>
<% end %>

app/views/users/_user_login_info.erb
<li><%= link_to "Articles", articles_path %></li>
<li><%= link_to "Forum", forums_path %></li>

<% if user_signed_in? %>
  <li><%= link_to "All users", users_path %></li>
  <li><%= link_to "My profile", current_user %></li>
  <li>
  <!-- Signed in as <%#= current_user.email %>. Not you? -->
  <%= link_to "Sign out", destroy_user_session_path %>
  </li>
<% else %>
  <li>
  <%= link_to "Sign in", user_session_path %>
  </li>
<% end %>

<% if can?(:create, User) %>
  <li><%= link_to("Add new user", new_user_path) %></li>
<% end %>

app/views/users/edit.html.erb
<%= nav_links(render 'users/user_login_info') %>
<%= subnav_links(render :partial => "forums/navigation", :locals => {:type => :edit_user}) %>


<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>


<%= form_for(@user, :html => { :multipart => :true }) do |f| %>
  <% if @user.errors.any? %>  
    <div id="errorExplanation">  
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>  
      <ul>  
        <% @user.errors.full_messages.each do |msg| %>  
          <li><%= msg %></li>  
        <% end %>  
      </ul>  
    </div>  
  <% end %>

  <%= render :partial => 'user_fields', :locals => { :f => f } %>

  <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
  <p><%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>

  <p><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i></p>
  <p><%= f.password_field :current_password %></p>

  <p><%= f.submit "Update" %></p>
<% end %>

app/views/users/index.html.erb
<%= nav_links(render 'users/user_login_info') %>
<%= subnav_links(render :partial => "forums/navigation", :locals => {:type => :edit_user}) %>


<table id="forum_table">
  <thead>
  <tr>
    <th class="thread_th">Name</th>
    <th class="thread_th">E-mail</th>
    <th class="thread_th">Roles</th>
  </tr>
</thead>
<tbody>
<% @users.each do |u| %>
  <tr>
    <td class="thread_td"><%= link_to_if(can?(:read, User), "#{u.name}", user_path(u.id)) {} %></td>
    <td class="thread_td"><%= "#{u.email}" %></td>
    <td class="thread_td"><%= "#{u.roles.collect{|r| r.name}}" %></td>
   </tr>
<% end %>
</tbody>
</table>

app/views/users/new.html.erb
<%= nav_links(render 'users/user_login_info') %>
<%= subnav_links(render :partial => "forums/navigation", :locals => {:type => :new_user}) %>

<h2>Register User</h2>


<%= form_for(@user, :html => { :multipart => :true }) do |f| %>
  <%#= error_messages(@user,"Could not register user") %>

	<%= render :partial => 'user_fields', :locals => { :f => f, :roles => @roles, :roles_new => @roles_new} %>

  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "Register" %></p>
<% end %>

app/views/users/show.html.erb
<%= nav_links(render 'users/user_login_info') %>
<%= subnav_links(render :partial => "forums/navigation", :locals => {:type => :show_user}) %>

<% if can?(:update, @user) %>
  <p>
  <%= link_to("Edit", edit_user_path(@user)) %>
  <% if can?(:destroy, @user) %>
    -
    <%= link_to("Delete", user_path(@user), :confirm => "Are you sure?", :method => :delete) %>
  <% end %>
  </p>
<% end %>

<h3><%= @user.name %></h3>


<table class="one-column-emphasis">
  <tbody>
    <tr>
      <td class="oce-first">Picture:</td>
      <td><%= image_tag @user.picture.url(:medium) %></td>
    </tr>
    <tr>
      <td class="oce-first">Email:</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td class="oce-first">Roles:</td>
      <td><%= @roles %></td>
    </tr>
    <tr>
      <td class="oce-first">Description:</td>
      <td><%= @user.description %></td>
    </tr>
    <% if can?(:see_timestamps,User) %>
      <tr>
        <td class="oce-first">Created at:</td>
        <td><%= @user.created_at %></td>
      </tr>
      <tr>
        <td class="oce-first">Last Sign In:</td>
        <td><%= @user.last_sign_in_at %></td>
      </tr>
      <tr>
        <td class="oce-first">Sign In Count:</td>
        <td><%= @user.sign_in_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>