config/routes.rb
SppForum::Application.routes.draw do

  

  devise_for :users,  :controllers => { :registrations => :users}
  
  resources :users
  resources :articles

  resources :forums do 
    resources :forum_threads
  end


  resources :forum_posts
  resources :forum_threads do
    resources :forum_posts
  end
  root :to => "articles#index"

end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
  belongs_to :forum
  belongs_to :user
  has_many :forum_posts
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  respond_to :html
  load_and_authorize_resource 

  def new
    @forum = Forum.find(params[:forum_id]) if can?(:create, ForumThread)
  end

  def edit
    @forum_thread = ForumThread.find(params[:id])
    if !(can?(:update, @forum_thread))
      @forum_thread = nil
    end
  end

  def show
    @forum_thread = ForumThread.find(params[:id]) if can?(:read, ForumThread)
  end

  def create
    #@forum_thread = ForumThread.new(params[:forum_thread])
    @forum_thread.forum_id = params[:forum_id]
    @forum_thread.user = current_user
    respond_to do |format|
      if can?(:create, ForumThread) and @forum_thread.save
        format.html {redirect_to forum_path(@forum_thread.forum), :notice => "Thread created" }
      else
        format.html {render :action => :new}
      end
    end
  end

  def update
    @forum_thread = ForumThread.find(params[:id])

    respond_to do |format|
      if can?(:update, @forum_thread) and @forum_thread.update_attributes(params[:forum_thread]) 
        format.html {redirect_to forum_thread_path(@forum_thread), :notice => "Thread updated!" }
      else
        format.html {render :action => :edit}
      end
    end
  end
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper

  def get_user_post_text(user)
    if user
      text = ""
      text += image_tag user.picture.url(:thumb) + "<br />" if user and user.picture.exists?
      text += "<strong>" + link_to(user.name, user) + "</strong>" if user.name
      text += "<br />Posts: "
      if user.forum_posts and (user.forum_posts).length > 0
        text += (user.forum_posts.length).to_s
      else
        text += "0"
      end
      return text
    else
      return "-"
    end
  end

end

app/views/forum_threads/edit.html.erb
<% nav_links raw(render "users/user_login_info") %>

<% forum = @forum_thread.forum %>
<%= subnav_links raw(render :partial => "forums/navigation", :locals => {:type => :edit_thread, :forum => forum, :thread => @forum_thread}) %>

<h1>Edit Thread</h1>
<%= form_for(@forum_thread, :action => "update") do |f|%>
  <p>
  <strong><%= f.label :title %></strong><br />
  <%= f.text_field :title %>
  </p>
  <p>
  <strong><%= f.label :body %></strong><br />
  <%= f.text_area :body %>
  </p>

  <p>
  <%= f.submit "Edit Thread" %>
  </p>
<% end %>

app/views/forum_threads/new.html.erb
<% nav_links raw(render "users/user_login_info") %>

<%= subnav_links raw(render :partial => "forums/navigation", :locals => {:type => :new_thread, :forum => @forum}) %>


<h1>New Thread</h1>
<%= form_for([@forum,@forum_thread]) do |f|%>
  <p>
  <strong><%= f.label :title %></strong><br />
  <%= f.text_field :title %>
  </p>
  <p>
  <strong><%= f.label :body %></strong><br />
  <%= f.text_area :body %>
  </p>

  <p>
  <%= f.submit "New Thread" %>
  </p>
<% end %>

app/views/forum_threads/show.html.erb
<% forum = @forum_thread.forum %>
<%= subnav_links raw(render :partial => "forums/navigation", :locals => {:type => :thread, :forum => forum, :thread => @forum_thread}) %>
<% nav_links raw(render "users/user_login_info") %>

<% if can?(:create, ForumPost) %>
  <p>
  <%= link_to "New reply" , new_forum_thread_forum_post_path(@forum_thread) %>
  </p>
<% end %>

<table id="forum_post_table">
  <tbody>
    <tr class="forum_column">
      <% thread_user = @forum_thread.user if @forum_thread %>
      <td class="forum_post_user_td">
        <%= raw (get_user_post_text(thread_user)) if thread_user %>
      </td>
      <td class="forum_post_td"><strong><%= @forum_thread.title %></strong> at <%= @forum_thread.created_at %><br /><%= @forum_thread.body %>
      <% thread_was_updated = (@forum_thread.updated_at != @forum_thread.created_at) %>
      <% if can?(:update, @forum_thread) or thread_was_updated %>
          <br /><br />
          <%= link_to("Edit", edit_forum_thread_path(@forum_thread)) if can?(:update, @forum_thread) %>
          <% if thread_was_updated %>
            <i>(last edit at <%= @forum_thread.updated_at %>)</i>
          <% end %>
      <% end %>
      </td>
    </tr>
  <% @forum_thread.forum_posts.each do |f| %>
    <tr class="forum_column">
      <td class="forum_post_user_td">
      <%= raw (get_user_post_text(f.user)) if f %>
      </td>
      <td class="forum_post_td"><strong><%= f.title %></strong> at <%= f.created_at %><br /><%= f.body %>
        <% post_was_updated = (f.updated_at != f.created_at) %>
        <% if can?(:update, f) or post_was_updated %>
          <br /><br />
          <%= link_to("Edit", edit_forum_thread_path(f)) if can?(:update, f) %>
          <% if post_was_updated %>
            <i>(last edit at <%= f.updated_at %>)</i>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<% if can?(:create, ForumPost) %>
  <p>
  <%= link_to "New reply" , new_forum_thread_forum_post_path(@forum_thread) %>
  </p>
<% end %>